### ISSUE TITLE
Multiline copyrights not supported for check and fix

### ISSUE THREAD

**Issue by fkuatspyro** [Spyro-Soft/scargo#100]
**Describe the bug**
Multi-line copyrights are not supported by check and fix command.

**To Reproduce**
1. Create empty .h file.
2. Add multiline copyright in `scargo.toml` and run `scargo update`
```
[check.copyright]
description = """ 
Copyright 
this is 
multi-line copyright
"""
exclude = []
```
3. run `scargo fix --copyright` ->Adds invalid copyright
4. run `scargo check --copyright` -> Still reports error for copyright 

**Expected behavior**
Scargo fix --copyright adds valid copyright when and scargo check validates it correctly.

**Comment by BohunSpyro** [comment]
scargo doesn't take updated copyrights from scargo.toml at all when command _scargo fix --copyright_

**Comment by BohunSpyro** [comment]
Fixed.

**Comment by jze-spyro** [comment]
No, it is **not** fixed.

> Expected behavior
> Scargo fix --copyright adds valid copyright when **and scargo check validates it correctly**.

Currently `scargo check` does not validate multiline copyright correctly.
