### ISSUE TITLE
Rework clang-format and clang-tidy checks

### ISSUE THREAD

**Issue by fkuatspyro** [Spyro-Soft/scargo#101]
**Is your feature request related to a problem? Please describe.**
Checkers for clang-format and clang-tidy use stdout to check if check passed which can lead to false positives. 

**Describe the solution you'd like**
Switch from using `subprocess.getoutput` to `subprocess.run` and check for the output.resultcode. For clang-format it will be necessary to add `--Werror ` flag to command and for clang-tidy this needs to be investigated.

**Comment by jze-spyro** [comment]
It turns out that `clang-tidy` returns a non-zero exit code on errors.
https://bugs.llvm.org/show_bug.cgi?id=27628
