### ISSUE TITLE
Code coverage is not calculated

### ISSUE THREAD

**Issue by kmc-spyro** [Spyro-Soft/scargo#137]
**Reproduction**

1. Create a new project, add new library and prepare UT for it
 - project attached
[ut_cov.zip](https://github.com/Spyro-Soft/scargo/files/11088769/ut_cov.zip)

2. Build and run UT:
```bash
scargo test
```

3. Open UT coverage report - `build/tests/ut-coverage.html`

**Error decription**
The generated code coverage report does not contain any data
![image](https://user-images.githubusercontent.com/96412835/228223030-93105ff7-d8d9-48d1-8a4e-84add873001d.png)

**Expected behavior**
The generated code coverage report contains report data

**Additional info**
When I prepared custom script with `lcov` I can get proper coverage data
```bash
#!/bin/bash

cd /workspace/build/tests

echo Create HTML report using lcov from
lcov --capture --directory . --rc lcov_branch_coverage=1 --output-file pkg.info
echo kicking out included files which are not interesting
lcov --remove pkg.info --output-file pkg_filtered.info --rc lcov_branch_coverage=1 '*/.conan/*' '*/tests/*' '/usr/include/*'

rm -R gcov_html_report
mkdir gcov_html_report
cd gcov_html_report
mv ../*.info .
genhtml pkg_filtered.info --rc genhtml_branch_coverage=1 -rc genhtml_legend=1 -rc genhtml_hi_limit=100 --output-directory . --demangle-cpp
```
![image](https://user-images.githubusercontent.com/96412835/228223223-6a8851a7-0c3d-4fb2-b490-700997a5c99d.png)

![image](https://user-images.githubusercontent.com/96412835/228223294-95598f09-09de-4d24-93ee-12846bfd58d2.png)

**Comment by jze-spyro** [comment]
This seems to be caused by #138 (but I'm not sure)
