### ISSUE TITLE
`cxxstandard` is not respected for tests

### ISSUE THREAD

**Issue by rap-spyro** [Spyro-Soft/scargo#154]
**Describe the bug**
`cxxstandard` in scargo.toml is not interpreted correctly for tests.

**To Reproduce**
1. Add `cxxstandard = "17"` to scargo.toml under `[tests]`.
1. `scargo update`
1. Note `SET (CMAKE_CXX_STANDARD 17)` is not present in tests/CMakelists.txt.
1. Change line in scargo.toml to `CMAKE_CXX_STANDARD = "17"`.
1. `scargo update`
1. Note CMAKE_CXX_STANDARD is set correctly.

**Expected behavior**
`cxxstandard = "17"` should work the same way as for the build profiles (setting `CMAKE_CXX_STANDARD` explicitly is a confusing workaround).

**Comment by jze-spyro** [comment]
@rap-spyro 
> Add cxxstandard = "17" to scargo.toml under [tests].

Is it required that tests have a separate cxxstandard setting? Currently they don't, which can be seen in the documentation: https://spyro-soft.github.io/scargo/scargo/scargo-toml.html#tests

Maybe it's enough to reuse cxxstandard defined under `[project]` for tests?

**Comment by rap-spyro** [comment]
It is possible that for the embedded target we would like to set a different setting, but I don't think it's needed at this point. Main issue is that it's not set for tests at all for now, so if you have a fix for that - reusing it would be enough.
