### ISSUE TITLE
Wrong compiler settings for ESP32

### ISSUE THREAD

**Issue by rap-spyro** [Spyro-Soft/scargo#157]
**Describe the bug**
Two bugs in one:
1. Generated `scargo.toml` sets `arm-none-eabi-*` for ESP32 targets.
1. `cc` and `cxx` in `scargo.toml` are not taken into account for ESP32 targets, `xtensa-esp32-elf-*` is used regardless of settings.

**To Reproduce**
1. Create new project for esp32: `scargo new --target esp32 cxxtest`
1. Check settings under `[project]` in scargo.toml:
```
cc  = "arm-none-eabi-gcc"
cxx = "arm-none-eabi-g++"
```
1. Change them to something unexpected:
```
cc  = "a-weird-compiler-gcc"
cxx = "a-weird-compiler-g++"
```
1. Run `scargo update`
1. Run `scargo build`. See that the project is build with xtensa compiler.

**Expected behavior**
`cc` and `cxx` are actually used in build. `xtensa-esp32-elf-*` is set by default for esp32 targets.

**Comment by jze-spyro** [comment]
This seems to be a complex issue. I can see that `project.cc` and `project.cxx` are only being used for x86, and the xtensa compilers are not even specified anywhere in our code. The cmakefiles specifying them are generated by esp-idf, which, as far as I understand, we have little control over.

**Comment by rap-spyro** [comment]
If so, I don't think this needs to be solved now, I'm not aware of any project that uses a different compiler for the ESP32.

That said, it shouldn't be misleading. So to fix this, I'd suggest removing references to `arm-none-eabi-*` (potentially replacing them with `xtensa-esp32-elf-*`) and adding a warning that esp-idf will overwrite this setting.
