### ISSUE TITLE
decrease size of the docker images

### ISSUE THREAD

**Issue by aaksenczuk** [Spyro-Soft/scargo#190]
**Is your feature request related to a problem? Please describe.**
check if there is a possibility to decrease the size of the docker for each target.

**Describe the solution you'd like**
start with removing all unused libraries and binaries from the docker image-building process. In the next step, check if we can optimize some of the Layers by integrating them, etc.

**Comment by jze-spyro** [comment]
I think the first step should be to decide if we really need to use the ubuntu image and not something lighter.
