### ISSUE TITLE
scargo flash --no-erase option

### ISSUE THREAD

**Issue by JakubZurkowski-spyro** [Spyro-Soft/scargo#201]
**Is your feature request related to a problem? Please describe.**
`scargo flash` command erases whole stm32 memory overwriting my bootloader code. I need to flash only my part of memory.

**Describe the solution you'd like**
Add `--no-erase` option for `scargo flash` command which would skip `st-flash erase` command.

**Comment by jobspyrosoft** [comment]
will be tested after release
