### ISSUE TITLE
[stm32] scargo debug can't find cfg for my target

### ISSUE THREAD

**Issue by JakubZurkowski-spyro** [Spyro-Soft/scargo#202]
**Describe the bug**
I'm working on STM32L073RZT6 microcontroller and the debugger should use target/stm32l0.cfg file. Instead it tries target/stm32l0x.cfg.

**Expected behavior**
The `scargo debug` command should check if `target/{self._chip[:7].lower()}x.cfg` exists and if not - try `target/{self._chip[:7].lower()}.cfg`

**Comment by jobspyrosoft** [comment]
Will be tested after release
