### ISSUE TITLE
Add possibility for user to edit compilation flags

### ISSUE THREAD

**Issue by KonradTajstra** [Spyro-Soft/scargo#228]
**Is your feature request related to a problem? Please describe.**
E.g. when building unit tests, it is not possible to set -jX flag which is by default set to max cpu cores (in my end is -j20)

**Describe the solution you'd like**
Possibility to modify flags

**Comment by aaksenczuk** [comment]
propose solution: we taking flag "build_core_no = int "from scargo.toml which is then used with cmake: cmake build . -j<build_core_no>

**Comment by jze-spyro** [comment]
I suggest using some other option name (above all, `no` suggests an ordinal, rather than a cardinal). For example `max_build_jobs` or `max_parallel_processes`.
https://cmake.org/cmake/help/latest/manual/cmake.1.html#cmdoption-cmake-build-j

**Comment by aaksenczuk** [comment]
agree

**Comment by rap-spyro** [comment]
Fixed in #235
