### ISSUE TITLE
A warning while using scargo build in docker

### ISSUE THREAD

**Issue by jobspyrosoft** [Spyro-Soft/scargo#230]
**Describe the bug**
When using scargo build in docker there is error visible

```
/usr/local/lib/python3.8/dist-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.0.0) or chardet (None)/charset_normalizer (3.1.0) doesn't match a supported version!
  warnings.warn(
```

**Comment by jze-spyro** [comment]
@jobspyrosoft 
You didn't include any reproduction steps. I'm running `scargo build` in docker and I'm not getting this message.

**Comment by jobspyrosoft** [comment]
For me it's just like this:
```
scargo new my_project
cd my_project
scargo docker run
scargo build
```

**Comment by jze-spyro** [comment]
I can't reproduce it. After the same steps I have `urllib3==1.26.16` installed, which doesn't cause this problem.
