### ISSUE TITLE
Scargo debug cannot find .elf

### ISSUE THREAD

**Issue by jobspyrosoft** [Spyro-Soft/scargo#239]
**Describe the bug**
when running scargo debug got this error
`scargo ERROR: Binary /workspace/build/Debug/bin/bin.elf does not exist`

contents of Debug/bin/
stm32project3.bin  stm32project3.elf  stm32project3.hex

**To Reproduce**
```
scargo new stm32project3 --bin bin --lib lib --target stm32
cd stm32project3
scargo docker run
scargo build --profile Debug
scargo debug
```

**Comment by jze-spyro** [comment]
It seems that it's not a problem with debug, but with build. It should build `bin.elf`, not `stm32project3.elf`.

**Comment by jze-spyro** [comment]
I'm not sure what's the binary file name supposed to be, should it be the project name or `bin_name`.
