### ISSUE TITLE
Unexpected message during docker startup

### ISSUE THREAD

**Issue by aaksenczuk** [Spyro-Soft/scargo#260]
**Describe the bug**
scargo version: 1.6.0
I'm getting following message when entering the docker:
/usr/lib/python3/dist-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

**To Reproduce**
1) scargo new presp32 --target esp32
2) scargo docker run

**Expected behavior**
This message should not pop up in the console during docker startup

**Comment by KonradTajstra** [comment]
What pops up in 1.6.5 is:
```
/opt/esp-idf/tools/check_python_dependencies.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
```

**Comment by KonradTajstra** [comment]
Fixed in https://github.com/Spyro-Soft/scargo/pull/347
