### ISSUE TITLE
[stm32] clang tidy still doesn't load compilation database

### ISSUE THREAD

**Issue by JakubZurkowski-spyro** [Spyro-Soft/scargo#261]
Issue #200 seems not fixed properly. In stm32 project I still get clang-tidy errors caused by missing compilation_commands.json

Probably the issue is that fix checks "esp32" as target.family instead of "stm32": [scargo/commands/check.py:302](https://github.com/Spyro-Soft/scargo/blob/d010e582857eb1534a2b9c8bcb6a1a24a2ad1623/scargo/commands/check.py#L302)

Besides, `compile_commands.json` is inside `./build/Debug` directory, not `./build/` (see: [scargo/commands/check.py:298](https://github.com/Spyro-Soft/scargo/blob/d010e582857eb1534a2b9c8bcb6a1a24a2ad1623/scargo/commands/check.py#L298)).

**Comment by KonradTajstra** [comment]
Fixed in https://github.com/Spyro-Soft/scargo/pull/336
