### ISSUE TITLE
[UT] Test gen -m, --mock FILE

### ISSUE THREAD

**Issue by aaksenczuk** [Spyro-Soft/scargo#264]
**Is your feature request related to a problem? Please describe.**
Write UT:
Generate mock of the chosen file. The .h or .hpp file shall be used. It will then generate mock in tests/mock folder with a path mirroring the sources.

**Describe the solution you'd like**
UT

**Additional context**
UT of the ut gen - scargo.file_generators.mock_gen

**Comment by MichalMendrala** [comment]
Basic tests implemented
