### ISSUE TITLE
[IT] It for full test flow

### ISSUE THREAD

**Issue by aaksenczuk** [Spyro-Soft/scargo#266]
**Is your feature request related to a problem? Please describe.**
Write a happy path for test generation and running 

**Describe the solution you'd like**
TC:
1) take the source for test - class with .h file where the interface for the test is defined
2) generate UT using gen -u command for this file
3) generate mock using gen -m for this file 
4) run the test and check if pass and new test is included

**Additional context**
new it in test folder

**Comment by MichalMendrala** [comment]
Done during work on: https://github.com/Spyro-Soft/scargo/issues/285
