### ISSUE TITLE
scargo command not found after pip install

### ISSUE THREAD

**Issue by psugrg** [Spyro-Soft/scargo#280]
**Describe the bug**
`scargo` command not found after `pip install scargo` on a fresh Ubuntu system

**To Reproduce**
1. Install a fresh Ubuntu on a VM
2. Install `scargo` using [installation instruction](https://github.com/Spyro-Soft/scargo#installation)
3. Try to run `scargo new test` -> command not found

**Expected behavior**
The installation process should guide the user what to do (e.g. to add a correct path to PATH)

**Comment by KonradTajstra** [comment]
Added guides to documentation in https://github.com/Spyro-Soft/scargo/pull/350
