### ISSUE TITLE
[esp32] MQTT connection fails with "Failed to verify peer certificate!" error

### ISSUE THREAD

**Issue by czeslaw-spyro** [Spyro-Soft/scargo#282]
**Describe the bug**
MQTT connection fails with "Failed to verify peer certificate!" error
See log:
I (17388) MQTT: MQTT_EVENT_BEFORE_CONNECT
E (18868) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x2700
I (18878) esp-tls-mbedtls: Failed to verify peer certificate!
E (18878) esp-tls: Failed to open new connection
E (18878) TRANSPORT_BASE: Failed to open a new connection
E (18888) MQTT_CLIENT: Error transport connect
I (18898) MQTT: MQTT_EVENT_ERROR
I (18898) MQTT: Last error code reported from esp-tls: 0x801a
I (18898) MQTT: Last tls stack error number: 0x2700
I (18898) MQTT: Last captured errno : 0 (Success)
I (18898) MQTT: MQTT_EVENT_DISCONNECTED

**To Reproduce**
Generate certs with command:
**scargo gen --certs <dev id as string>**
than build fs and image
then run the app.

**Expected behavior**
MQTT connection is successfull.

**Additional context**
Most likely it is related with https://github.com/Spyro-Soft/scargo/issues/281 Azure IoT root certificate: Migrate from the Baltimore CyberTrust Root to the DigiCert Global G2 Root

**Comment by KonradTajstra** [comment]
Fixed in https://github.com/Spyro-Soft/scargo/pull/284
