### ISSUE TITLE
[Test Scenario] Basic full flow new project bin only tests

### ISSUE THREAD

**Issue by MichalMendrala** [Spyro-Soft/scargo#290]
**Is your feature request related to a problem? Please describe.**
Need to define, discuss and review of test for new project with bin only

**Describe the solution you'd like**
Issue which will store test description

**Test case description**

From backward compatibility tests: [backward_compatibility_test](https://github.com/Spyro-Soft/scargo/issues/286) differs only at few places:
- copying old test project not creating new project by scargo command
- expected name of binary file is taken from existing in root project directory CMakeLists.txt file
- first fix command test is allow to return that some issues was found and fixed -  each copied project may have different issues in files
- gen -u test is skipped - each copied project may have different structure, so different ut will be generated

**TO DO**
- tests for other esp series: c, c2, s, s2,
- many tests are very basic and checking just if command do not return errors, so some mor detailed tests should be done in future
- what to do with comands: 
  - debug,
  - flash,

**Suggestions**
- maybe also change "cxxstandard" to see if CMakelits.txt was updated? or leave it for ut?

For all platforms/targets (x86, esp32 and stm32)

**1. test_cli_help**

- Perform command: **new -h**
-  Check if command finish without error just to check if scargo commands are working

**2. test_cli_new**

- Perform command: **new TEST_PROJECT_NAME --target TARGET_ID --bin BIN_NAME**
- Check if command finish with exit code == 0 (no error)
-  Check if following files and directories were created:

> - ../TEST_PROJECT_NAME/CMakeLists.txt
> - ../TEST_PROJECT_NAME/conanfile.py
> - ../TEST_PROJECT_NAME/LICENSE
> - ../TEST_PROJECT_NAME/README.md
> - ../TEST_PROJECT_NAME/scargo.lock - this should be created by update command (but CLI new call new and update)
> - ../TEST_PROJECT_NAME/scargo.toml
> - ../TEST_PROJECT_NAME/src(or main for esp32)/CMakeLists.txt
> -  ../TEST_PROJECT_NAME/src(or main for esp32)/BIN_NAME.cpp
> - ../TEST_PROJECT_NAME/tests/CMakeLists.txt
> - ../TEST_PROJECT_NAME/tests/conanfile.py
> - ../TEST_PROJECT_NAME/tests/it/CMakeLists.txt
> - ../TEST_PROJECT_NAME/tests/ut/CMakeLists.txt
> - ../TEST_PROJECT_NAME/tests/mocks/CMakeLists.txt
> - ../TEST_PROJECT_NAME/tests/mocks/static_mock/CMakeLists.txt
> - ../TEST_PROJECT_NAME/tests/mocks/static_mock/static_mock.h

**3. test_cli_docker_run**

- Perform command: **docker run**
- Check if command finish with exit code == 0 (no error)

**4. test_cli_update**

- Perform command: **update**
- Check if command finish with exit code == 0 (no error)

**5. test_cli_build**

- Perform command: **build**
- Check if command finish with exit code == 0 (no error)
- Check if dir ../build/Debug/bin ( ../build/Debug for esp32) created and containing:

> - BIN_NAME file for x86
> - BIN_NAME.bin, BIN_NAME.elf and BIN_NAME.hex for stm32
> - BIN_NAME.bin, BIN_NAME.elf and BIN_NAME.map for esp32

**6. test_cli_clean**

- Perform command: **clean**
- Check if command finish with exit code == 0 (no error)
- Check if ../build dir was removed

**7. test_cli_build_profile_debug**

- Perform command: **build --profile=Debug**
- Check if command finish with exit code == 0 (no error)
- Check if dir ../build/Debug/bin ( ../build/Debug for esp32) created and containing:

> - BIN_NAME file for x86
> - BIN_NAME.bin, BIN_NAME.elf and BIN_NAME.hex for stm32
> - BIN_NAME.bin, BIN_NAME.elf and BIN_NAME.map for esp32

**8. test_debug_bin_file_format_by_objdump_results**

- run objdump command in docker under bin file location

> for x86 "objdump BIN_NAME -a"
> for stm32 "/opt/gcc-arm-none-eabi/bin/arm-none-eabi-objdump BIN_NAME -a"
> for esp32 "/opt/esp-idf/tools/xtensa-esp32-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-objdump BIN_NAME -a"

- check if expected bin file format in objdumps results

> for x86 "elf64-x86-64"
> for stm32 "elf32-littlearm"
> for esp32 "elf32-xtensa-le"

**9. test_cli_clean_after_build_profile_debug**

- Perform command: **clean**
- Check if command finish with exit code == 0 (no error)
- Check if ../build dir was removed

**10. test_cli_build_profile_release**

- Perform command: **build --profile=Release**
- Check if command finish with exit code == 0 (no error)
- Check if dir ../build/Release/bin ( ../build/Release for esp32) created and containing:

> - BIN_NAME file for x86
> - BIN_NAME.bin, BIN_NAME.elf and BIN_NAME.hex for stm32
> - BIN_NAME.bin, BIN_NAME.elf and BIN_NAME.map for esp32

**11. test_release_bin_file_format_by_objdump_results**

- run objdump command in docker under bin file location

> for x86 "objdump BIN_NAME -a"
> for stm32 "/opt/gcc-arm-none-eabi/bin/arm-none-eabi-objdump BIN_NAME -a"
> for esp32 "/opt/esp-idf/tools/xtensa-esp32-elf/esp-2021r2-patch5-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-objdump BIN_NAME -a"

- check if expected bin file format in objdumps results

> for x86 "elf64-x86-64"
> for stm32 "elf32-littlearm"
> for esp32 "elf32-xtensa-le"

**12. test_cli_clean_after_build_profile_release**

- Perform command: **clean**
- Check if command finish with exit code == 0 (no error)
- Check if ../build dir was removed

**13. test_cli_fix**

- Perform command: **fix**
- Check if command finish with exit code == 0 (no error)
- for newly created projects (coppied projs sometimes has errors here) check if no problems was found and fixed

**14. test_cli_check**

- Perform command: **check**
- Check if command finish with exit code == 0 (no error)
- Check if "No problems found" returned in output

**14. test_cli_test**

- Perform command: **test**
- Check if command finish with exit code == 0 (no error)
- Check if "No tests were found!!!" returned in output

**15. test_precondition_add_new_profile**

- define NEW_PROFILE_CFLAGS as string "-gdwarf"
- define NEW_PROFILE_CXXFLAGS as string "-ggdb"
- using add_profile_to_toml function adding new profile with name NEW_PROFILE_NAME and cflags=NEW_PROFILE_CFLAGS and cxxflags=NEW_PROFILE_CXXFLAGS

**16. test_update_after_adding_new_profile**

- Perform command: **update**
- Check if command finish with exit code == 0 (no error)
- check if in newly created profile conan file under ..config/conan/profiles/TARGET_ID_NEW_PROFILE_NAME expected flags are stored by checking if cflags contains NEW_PROFILE_CFLAGS and cxxflags contains NEW_PROFILE_CXXFLAGS (for esp32 if filess WORKAROUND_FOR_ESP32_C_FLAGS and WORKAROUND_FOR_ESP32_CXX_FLAGS contains correspondingly NEW_PROFILE_CFLAGS and  NEW_PROFILE_CXXFLAGS)

**17. test_cli_build_profile_new**

- Perform command: **build --profile=NEW_PROFILE_NAME **
- Check if command finish with exit code == 0 (no error)
- Check if dir ../build/NEW_PROFILE_NAME/bin ( ../build/NEW_PROFILE_NAME for esp32) created and containing:

> - BIN_NAME file for x86
> - BIN_NAME.bin, BIN_NAME.elf and BIN_NAME.hex for stm32
> - BIN_NAME.bin, BIN_NAME.elf and BIN_NAME.map for esp32

**18. test_flags_stored_in_commands_file**

- open scargo,toml file and default cflags, default cxxflags and cxxstandard values
- Check if file .conan/profiles/x86_new containing expected "cflags" and "cxxflags" values - TODO???
- open ../build/NEW_PROFILE_NAME/compile_commands.json file and check for all entries: 

> if file is c file than command should contain default cflags and defined by new profile NEW_PROFILE_CFLAGS
> if file is c++ file than command should contain default cxxflags and defined by new profile NEW_PROFILE_CXXFLAGS
> if file is c++ file than command should contain cxxstandard from toml file

**19. test_cli_gen_u_option_nothing_to_gen**

- perform command: **gen -u path_to_src_or_main_dir**
- check if command finish with exit code == 0 (no error)
- check if under path ..tests/ut only CMakeLists.txt file exist

**20. test_precondition_create_and_fix_dummy_test_lib_h_file**

- create empty file with .h extension and name TEST_DUMMY_LIB_H_FILE
- perform command: **fix**
- check if command finish with exit code == 0 (no error)
- perform command: **check**
- check if command finish with exit code == 0 (no error)

**21. test_cli_gen_u_option**

- perform command: **gen -u path_to_src_or_main_dir**
- check if command finish with exit code == 0 (no error)
- check if under path ..tests/ut exist file ut_TEST_DUMMY_LIB_H_FILE.cpp

**22. test_cli_test_some_tests_to_run**

- Perform command: **test**
- Check if command finish with exit code == 0 (no error)
- Check if "100% tests passed, 0 tests failed out of 1" returned in output

**23. test_cli_gen_m_option**

- Perform command: **gen -m path_to_TEST_DUMMY_LIB_H_FILE.h**
- Check if command finish with exit code == 0 (no error)
- check if ../tests/mocks/TEST_DUMMY_LIB_H_FILE.h exist
- check if ../tests/mocks/mock_TEST_DUMMY_LIB_H_FILE.h exist
- check if ../tests/mocks/mock_TEST_DUMMY_LIB_H_FILE.cpp exist

**24. test_cli_gen_c_option**

- Perform command: **gen -c TEST_DEVICE_ID**
- Check if command finish with exit code == 0 (no error)
- check if ../build/fs/ca.pem exist
- check if ../build/fs/device_cert.pem exist
- check if ../build/fs/device_priv_key.pem exist
- check if ../build/certs/azure/TEST_DEVICE_ID-root-ca.pem exist

**25. test cli_gen_fs_option**

- Perform command: **gen -f**
- Check if command finish with exit code == 0 (no error)
- if target is esp32 than check if under ../build path file spiffs.bin exist for othher targets check if "Gen --fs command not supported for this target yet" is in output

**26. test_cli_gen_b_option**

- not implemented yet

**27. test_cli_check_after_gen**

- Perform command: **check**
- Check if command finish with exit code == 0 (no error)
- Check if "No problems found" returned in output

**28. test_cli_run_new_proj**

- Perform command: **run**
- if target is x86 than command should finish with exit code == 0 (no error) and "Hello World!" should be present in output
- if target is stm32 esp32 than command should finish with exit code == 1 (error) and "Run project on x86 architecture is not implemented for {test_state.target_id.value} yet" in output

**29. test_cli_check_fail_for_copied_fix_files**

- coppy files from  /tests/test_data/test_projects/test_files/fix_test_files into src (main for esp32) dir
- perform command:  **check**
- command should finish with exit code == 1 (error)
- output should contain "clang-format: 3 problems found"
- output should contain "copyright: 3 problems found"
- output should contain "pragma: 1 problems found"

**30. test_cli_fix_copied_fix_files**

- perform command:  **fix**
- command should finish with exit code == 0 (no error)
- output should contain "Finished clang-format check. Fixed problems in 3 files."
- file fix_test_bin.cpp under src/main dir should contain copyright text from toml file
- file fix_test_lib.cpp under src/main dir should contain copyright text from toml file
- file fix_test_lib.h under src/main dir should contain copyright text from toml file
- file fix_test_lib.h under src/main dir should contain "#pragma once" string

**31. test_cli_check_pass_after_fix**

- perform command:  **check**
- command should finish with exit code == 0 (no error)
- in output "No probles found!" string should be present

**32. test_cli_doc**

- perform command:  **doc**
- command should finish with exit code == 0 (no error)
- check if file ../build/doc/html/index.html exist
- check if file ../build/doc/latex/Makefile exist
- check if file ../build/doc/Doxyfile exist

**Bugs found by this test:**

- certs not generated: [issue_297](https://github.com/Spyro-Soft/scargo/issues/297)
- inconsistent naming of bin files: [issue_298](https://github.com/Spyro-Soft/scargo/issues/298)
- need to coppy IDF file for esp32 to update and build project - fixed before issue raised in GH
- when building new profile with not standard conan name (like New) than some bin files created under Debug profile instead of New profile: [issue_299](https://github.com/Spyro-Soft/scargo/issues/299)
- compile flags from profile not used for building esp32: [issue_304](https://github.com/Spyro-Soft/scargo/issues/304)

**Comment by KonradTajstra** [comment]
Step 16 - What can be also checked is if "config/conan/profiles/<target>_<profile> file was created

**Comment by KonradTajstra** [comment]
Step 18 - Suggestion: consider renaming to test_flags_stored_in_compile_commands_file - to be more verbose

**Comment by KonradTajstra** [comment]
Step 23. and 25. - These steps should be executed in reversed order - first gen --certs, then gen --fs. This could be even combined in one step. For stm32 and x86 '--gen' is not supported so flow could be as described in step 25. But for esp32 I suggest following:
- execute step 25, check if certs are generated,
- add some dummyfile to main/fs
- check if build/fs contains dummyfile
- check spiffs.bin like in step 23

**Comment by MichalMendrala** [comment]
> Step 18 - Suggestion: consider renaming to test_flags_stored_in_compile_commands_file - to be more verbose
> 
> I will put definition in tests



> Step 18 - Suggestion: consider renaming to test_flags_stored_in_compile_commands_file - to be more verbose

You are right, I will put definition of this flags.

**Comment by MichalMendrala** [comment]
All suggestions implemented, thanks @KonradTajstra for great cooperation during realization of this task.

**Comment by MichalMendrala** [comment]
Done
