### ISSUE TITLE
Missing digiroot.pem file while generating certs

### ISSUE THREAD

**Issue by MichalMendrala** [Spyro-Soft/scargo#297]
**Describe the bug**
Missing digiroot.pem file while generating certs by **scargo gen -c DUMMY:DEVICE:ID:12345**
![image](https://github.com/Spyro-Soft/scargo/assets/89970908/fa4a51eb-7cf1-4e00-9622-0a09ed7349b5)

**To Reproduce**
- Create new project for x86by cli **scargo new new_proj --target=x86 --bin=test_bin** command (binary project)
- perform **scargo docker run** command
- perform **scargo build** command
- perform **scargo gen -c DUMMY:DEVICE:ID:12345** command

**Expected behavior**
Command **scargo gen -c DUMMY:DEVICE:ID:12345** should finish without error and cert should be generated

**Additional context**

**Comment by KonradTajstra** [comment]
Fixed in https://github.com/Spyro-Soft/scargo/pull/301
