### ISSUE TITLE
Inconsistent naming of bin files across targets

### ISSUE THREAD

**Issue by MichalMendrala** [Spyro-Soft/scargo#298]
**Describe the bug**
Inconsistent naming of bin files across targets, for x86 projects bin files have name same as source file name, but for esp32 and for stm32 bin file name is same as project name

**x86 project:**
![MicrosoftTeams-image (8)](https://github.com/Spyro-Soft/scargo/assets/89970908/40b1fab1-dead-4665-8071-179e1b328c02)

**stm32 project:**
![MicrosoftTeams-image (6)](https://github.com/Spyro-Soft/scargo/assets/89970908/41a7a3ad-961d-4757-8ee2-aebcab038f12)

**esp32 project:**
![MicrosoftTeams-image (7)](https://github.com/Spyro-Soft/scargo/assets/89970908/d96d061c-c84f-4ed9-97b6-39639b59245b)

**To Reproduce**

For each target from list [x86, stm32, esp32]
- Create new project for selected target by cli scargo new new_proj --target=target --bin=test_bin command (binary project)
- perform **scargo docker run** command
- perform **scargo build** command
- go to ./build/Debug/bin and list files, compare their names

**Expected behavior**
Naming should be consistent probably name of bin file should be same as name of projest, so esp32 and stm32 seems to be working fine, but x86 differs from this behaviour.

**Additional context**
This is just a suggestion if there is any reasonable reason why we have this inconsistency than it should be considered if fixing this issue is worth work.

**Comment by KonradTajstra** [comment]
Fixed in https://github.com/Spyro-Soft/scargo/pull/302
