### ISSUE TITLE
For esp32 compile_commands.json do not contain expected for used profile flags 

### ISSUE THREAD

**Issue by MichalMendrala** [Spyro-Soft/scargo#304]
**Describe the bug**
For esp32 compile_commands.json do not contain expected for used profile flags. Other platforms seems to working fine.

**To Reproduce**
- Create new project by cli scargo new **new_proj --target=esp32 --bin=test_bin** command (binary project)
- perform **scargo docker run** command
- add new profile by **add_profile_to_toml** function stored under scargo/tests/it/utils.py `add_profile_to_toml("New", "cflags", "cxxflags", "-g", "-g")`
- perform **scargo build --profile=New** command
- go to ./build/ folder check compile_commands.json content, no expected flags in command

**Expected behavior**
-  compile_commands.json file under "command" key should contain flags from profile (-g -g in this example)

**Comment by KonradTajstra** [comment]
Fixed in: https://github.com/Spyro-Soft/scargo/pull/312
