### ISSUE TITLE
Files in home/${USER} directory lack permissions in some environments

### ISSUE THREAD

**Issue by KonradTajstra** [Spyro-Soft/scargo#330]
**Describe the bug**
For some people there are permissions missing in docker (problem spotted on Ubuntu 22 on VM)

When building project using scargo following error might occur:

> Python requirements from /opt/esp-idf/requirements.txt are satisfied.
>CMake Error at /opt/esp-idf/tools/cmake/build.cmake:452 (message):
>  ERROR: Failed to create cache directory:
>  /home/robert/.cache/Espressif/ComponentManager
>Call Stack (most recent call first):
>  /opt/esp-idf/tools/cmake/project.cmake:384 (idf_build_process)
>  CMakeLists.txt:64 (project)
>-- Configuring incomplete, errors occurred!
>See also "/workspace/build/Debug/build/Debug/CMakeFiles/CMakeOutput.log".
>ERROR: conanfile.py (esp32-ihub-scargo/0.1.0): Error in build() method, line 33
>    cmake.configure()
>    ConanException: Error 1 while executing cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/opt/esp-idf/tools/cmake/toolchain-
>esp32.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "/workspace/."
>scargo ERROR: Unable to build exec file

When building docker image this error might occur during 'RUN az extension add --name azure-iot'
> error 13 permission problem during create dir

Workaround for building project:
- Check in the container if directories in home/user are owned by a root, if yes use chown to change the ownership to correct user

Workaround for building image:
- Put this line before 'RUN az extension add --name azure-iot
- RUN chmod 777 /home/${USER}

**To Reproduce**
Detailed steps to reproduce the behavior, make sure to include commands and arguments that led to the issue as well as relevant commands that might have been ran beforehand.

**Expected behavior**

**Additional context**

**Comment by sho-spyrosoft** [comment]
I can't reproduce the bug.
