### ISSUE TITLE
Different mypy output from ci and pre-commit

### ISSUE THREAD

**Issue by fkuatspyro** [Spyro-Soft/scargo#380]
**Describe the bug**
mypy check on CI is passing, while mypy check in precommit hook is failing

**To Reproduce**
1. checkout develop
2. pre-commit run -a (setup pre-commit if not already)

**Expected behavior**
pre-commit hook and CI are running mypy in same way

**Additional context**

**Comment by sho-spyrosoft** [comment]
In the CI the mypy won't be executed.
![image](https://github.com/Spyro-Soft/scargo/assets/147142096/014fe59b-5e4a-41a3-841d-c2e6483ddf4f)

**Comment by fkuatspyro** [comment]
No, this is not the reason as requirements.txt is generated using pip-compile `pip-compile --all-extras --output-file=ci/requirements.txt pyproject.toml`.
Same pacakges will be installed if you install using pip based on pyproject.toml `pip install .[dev,doc]` which is what I do.
![image](https://github.com/Spyro-Soft/scargo/assets/123727166/59e596c5-b95b-4485-9709-b0fa289cfd16)
