### ISSUE TITLE
Can't exclude directories outside /workspace for clang tidy check

### ISSUE THREAD

**Issue by bkresaj** [Spyro-Soft/scargo#387]
**Describe the bug**
Can't exclude directories outside /workspace for clang tidy check.

**To Reproduce**
Before running scargo check --clang-tidy I have tried to exclude it inside scargo.toml file in [check] or [check.clang-tidy] section using relative path for directory outside of /workspace(scargo update was run so scargo.lock file changed accordingly).

**Expected behavior**
I shouldn't get warning/errors for excluded directories from clang tidy check.

**Comment by fkuatspyro** [comment]
This is currently not supported by clang-tidy. Some relevant links:
https://github.com/llvm/llvm-project/issues/52959
https://itecnote.com/tecnote/c-ignore-clang-diagnostic-error-clang-tidy-caused-by-3rd-party-headers/
