### ISSUE TITLE
Scargo uses deprecated command 'conan user'

### ISSUE THREAD

**Issue by kmc-spyro** [Spyro-Soft/scargo#394]
**Describe the bug**
After upgrade to scargo 2.0 the new version of conan is used - 2.0.
The new conan version does not support `conan user` any more (`conan remote login` shall be used instead) - however scargo still tries to use `conan user`

**To Reproduce**
* Create a new project
* enter docker container
* run `scargo build`

**Expected behavior**
Proper credentials to conan repository is set.

**Comment by fkuatspyro** [comment]
Solved in Release 2.0.1
