### ISSUE TITLE
in-repo-conan-cache ignored in scargo-2.0

### ISSUE THREAD

**Issue by kmc-spyro** [Spyro-Soft/scargo#395]
**Describe the bug**
When upgraded to scargo 2.0 the option `in-repo-conan-cache` is ignored.

**To Reproduce**
* create a new project
* change `in-repo-conan-cache` option in `scargo.toml` to true
* execute `scargo update`
* run docker container
* try to build the project with `scargo build`
* the conan folder from the home directory is used instead of the one in the `/workspace/`

**Expected behavior**
Conan uses `/workspace/.conan2` folder for its configuration and cache

**Additional context**
Note - conan has been changed to conan 2.0 - CONAN_USER_HOME is not used any more.
In order to use another conan home folder another environment variable shall be set: 
`CONAN_HOME=/workspace/.conan2`
or
`CONAN_HOME=/workspace/.conan`

**Comment by fkuatspyro** [comment]
Solved in Release 2.0.1
