### ISSUE TITLE
Stm32 conan profiles with hardcoded paths

### ISSUE THREAD

**Issue by kmc-spyro** [Spyro-Soft/scargo#396]
**Describe the bug**
Conan profiles for stm32 target contain hard-coded paths:
```yml
[conf]
tools.build:cflags=["-Wall -Wextra -g"]
tools.build:cxxflags=["-Wall -Wextra -g"]
tools.cmake.cmaketoolchain:user_toolchain=["/workspace/config/conan/profiles/stm32_gcc_toolchain_wrapper.cmake"]
```
This causes that trying to build the project in any other folder than `/workspace` fails (for instance this is the case for CI/CD builds on GitLab.

**To Reproduce**
* Create a new project for stm32 target
* create container
* run container with different folder than `/workspace`, e.g.:
```bash
docker run -it -v `pwd`:/repo stm32-test-scargo-2-0-dev:1.0 bash
```
* try to build with `scargo build`
* 
**Expected behavior**
Build is successful. It uses proper toolchain file.

**Additional context**
Fix proposal (use $PROFILE_DIR variable
```yml
[conf]
tools.build:cflags=["-Wall -Wextra -g"]
tools.build:cxxflags=["-Wall -Wextra -g"]
tools.cmake.cmaketoolchain:user_toolchain=["$PROFILE_DIR/stm32_gcc_toolchain_wrapper.cmake"]
```

**Comment by fkuatspyro** [comment]
Solved in Release 2.0.1
