### ISSUE TITLE
Unnecessary build folder copying

### ISSUE THREAD

**Issue by kmc-spyro** [Spyro-Soft/scargo#420]
**Describe the bug**
On the branch for esp-idf-v5.1.1 - the build folder is copied with `copytree` python function. This function copies the whole build folder which takes time and consumes a lot of disk space.

Previously the command `cp -r -l` was used which just created hardlinks (fast and minimum disk usage).

Unfortunately this command is not working with the new esp-idf which during build creates some symbolic links to /opt/eps-idf files.
I suggest to fix this problem with adding `-P` option to copy which would no dereference symbolic links during copying - everything will work correctly, fast and not consuming so much disk space.

**Comment by aaksenczuk** [comment]
merge with idf-v5.1.1 branch
