### ISSUE TITLE
Animated gif in readme is nearly unreadable

### ISSUE THREAD

**Issue by jze-spyro** [Spyro-Soft/scargo#66]
[The gif included in readme](https://raw.githubusercontent.com/Spyro-Soft/scargo/develop/docs/source/_static/scargo_flow_docker.gif) appears to be a screencast done in high resolution, so in the browser it's nearly unreadable. I would suggest making a new one in lower resolution.

This is what it looks like:
![image](https://user-images.githubusercontent.com/125645748/219635801-6b879127-291d-40a9-abd1-ea2f1eb3c6a9.png)

**Comment by icesar-spyro** [comment]
This should be remade using https://asciinema.org/

**Comment by jze-spyro** [comment]
@icesar-spyro It's not possible to embed asciinema in a github readme (see https://github.com/asciinema/asciinema-server/issues/171#issuecomment-308422342).
If we want to have a readable and lightweight terminal animation, animated svg sounds like the best option. Maybe we can use https://github.com/nbedos/termtosvg.
