### ISSUE TITLE
Excludes for `scargo doc` don't work correctly

### ISSUE THREAD

**Issue by rkapuscik** [Spyro-Soft/scargo#79]
**Describe the bug**
Excludes for `scargo doc` don't work correctly, they are still parsed and used to build the documentation.

**To Reproduce**

1. Create a new scargo project.
1. Clone another repository as a dependency: `git clone --recurse-submodules https://github.com/FreeRTOS/FreeRTOS.git third-party/FreeRTOS
`
3. Add `exclude` section to the config:
```
echo "[doc]" >> scargo.toml
echo 'exclude = ["third-party"]' >> scargo.toml
```
1. Run `scargo update`.
1. Build the project (to create `build/`).
1. Run `scargo doc`.
1. Observe that both `build` and `third-party` are parsed.

**Expected behavior**
`build` and any `exclude` directories are omitted from the documentation build. Alternatively, only `src` is used.

**Comment by fkuatspyro** [comment]
Resolved in 1.0.7
